"""Add monthly_income and budget to user

Revision ID: 1af9464cff7b
Revises: 001_add_expenses
Create Date: 2026-05-27 01:04:13.498379

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '1af9464cff7b'
down_revision = '001_add_expenses'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_budget_category_id'), table_name='budget')
    op.drop_index(op.f('ix_budget_owner_id'), table_name='budget')
    op.drop_index(op.f('ix_category_owner_id'), table_name='category')
    op.drop_index(op.f('ix_expense_category_id'), table_name='expense')
    op.drop_index(op.f('ix_expense_expense_date'), table_name='expense')
    op.drop_index(op.f('ix_expense_owner_id'), table_name='expense')
    op.drop_index(op.f('ix_income_income_date'), table_name='income')
    op.drop_index(op.f('ix_income_owner_id'), table_name='income')
    
    # Add columns as nullable first
    op.add_column('user', sa.Column('monthly_income', sa.Float(), nullable=True))
    op.add_column('user', sa.Column('budget', sa.Float(), nullable=True))
    
    # Set default values for existing rows
    op.execute("UPDATE \"user\" SET monthly_income = 0.0 WHERE monthly_income IS NULL")
    op.execute("UPDATE \"user\" SET budget = 0.0 WHERE budget IS NULL")
    
    # Now make them NOT NULL
    op.alter_column('user', 'monthly_income', nullable=False)
    op.alter_column('user', 'budget', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'budget')
    op.drop_column('user', 'monthly_income')
    op.create_index(op.f('ix_income_owner_id'), 'income', ['owner_id'], unique=False)
    op.create_index(op.f('ix_income_income_date'), 'income', ['income_date'], unique=False)
    op.create_index(op.f('ix_expense_owner_id'), 'expense', ['owner_id'], unique=False)
    op.create_index(op.f('ix_expense_expense_date'), 'expense', ['expense_date'], unique=False)
    op.create_index(op.f('ix_expense_category_id'), 'expense', ['category_id'], unique=False)
    op.create_index(op.f('ix_category_owner_id'), 'category', ['owner_id'], unique=False)
    op.create_index(op.f('ix_budget_owner_id'), 'budget', ['owner_id'], unique=False)
    op.create_index(op.f('ix_budget_category_id'), 'budget', ['category_id'], unique=False)
    # ### end Alembic commands ###